### ISSUE TITLE
Amount Due was not properly reflected after dealer upgraded two memberships until admins 'saved'

### ISSUE THREAD

**Issue by jmdawson** [MidwestFurryFandom/mff-rams-plugin#100]
> On June 23 < Dealer > paid for their tables and four memberships, then upgraded two of the memberships to Shiny Sponsor. This posted an additional $440 due. On August 3 membership info for the other two memberships, including upgrades for both of them to Shiny Sponsor. However, the amount due was not increased immediately. When I went to check on this, after looking at the group page I clicked "save" and the additional $440 was then posted, and payment of the full $880 was made.
> 
> My question is, why was the initial $440 posted without any action on my part, but the second $440 needed me to save the group page before it was posted? Is this something that I'm going to have to do for future membership upgrades, or is it a one-time glitch in the system?

**Comment by kitsuta** [comment]
The answer to the question is that the group leader themselves probably saved the group on the group info page, but didn't realize that this is what updated the cost. If the group itself wasn't saved, its cost was not updated. PR #119 forces an update on the group's cost when the attendee is saved, so once that's in, manual intervention should no longer be needed.
