### ISSUE TITLE
Unable to set badge printed name on dealer page set up as group leader

### ISSUE THREAD

**Issue by jmdawson** [MidwestFurryFandom/mff-rams-plugin#109]
1. create a group through admin interface
1. set badge amount to 1
1. Complete group
1. Access badge from the group leader field at bottom of group
1. Fill out info. No badge name field is present
1. Unable to complete reg as the form fails validation.
<img width="1255" alt="screen shot 2018-08-18 at 13 42 18" src="https://user-images.githubusercontent.com/910490/44302429-e94ebb00-a2ed-11e8-9e03-3cdc3e128b5f.png">

**Comment by jmdawson** [comment]
Maybe we can sort this in Iteration 4. I'd like it, though it's probably not biting us too badly right now.

**Comment by kitsuta** [comment]
This is not a bug, we just don't have the Guest badge listed as a preassigned badge type in the config.

`preassigned_badge_types = 'attendee_badge','staff_badge','sponsor_badge','shiny_badge','friday','saturday','sunday'`
change to:
`preassigned_badge_types = 'attendee_badge','staff_badge','sponsor_badge','shiny_badge','friday','saturday','sunday','guest_badge'`

**Comment by jmdawson** [comment]
Documented this config in the wiki as well.
