### ISSUE TITLE
Change confirmation message for onsite registrations

### ISSUE THREAD

**Issue by ianlayton** [MidwestFurryFandom/mff-rams-plugin#132]
When used on site, when a registration is completed, it shows the following message "Your payment has been accepted, please proceed to the Preregistration desk to pick up your badge. This is incorrect for MFF as preregistration desk would only have preprinted badges. Can we please change the message to "Your registration and payment has been accepted, please continue through the at the door registration line to check in and receive your badge. Please have your ID ready."

Also, can we change the message when a person registers and wants to pay cash from "Thanks! Please queue in the cash line and have your photo ID and $XX ready" to  "Your registration has been accepted, please continue through the at the door registration line to check in, finish payment and received your badge. Please have your payment and ID ready."

**Comment by kitsuta** [comment]
We actually have a whopping five different messages we show people based on what they selected. After merging https://github.com/MidwestFurryFandom/rams/pull/287 we need to add these messages to configuration:

1. `at_door_prepaid_msg`: The first message in this issue, shown after they complete Stripe payment.
2. `at_door_cash_msg`: The second message in this issue, when they select 'Pay with cash.'
3. `at_door_manual_msg`: A message shown if they select 'Pay with credit card at the registration desk.'
4. `at_door_nopay_msg`: A message shown if the attendee's badge is free for some reason. This actually doesn't seem to happen to under-6 attendees, so it might be an extreme edge case.
5. `at_door_waived_msg`: A message shown after the `badge_price_waived` date. I'm not totally sure we set for MFF.

By the way, registering a badge for someone under 6 will currently tell you to have "$0" ready, so we may want to still include the price of the badge in the message. Also keep in mind that the messages auto-expire, so it might be a little inconvenient to have one that's very long.

**Comment by kitsuta** [comment]
Whoops, that PR wasn't meant to close this issue. 😬

**Comment by jmdawson** [comment]
I've deployed the requested prepaid and cash messages to staging. If there is language for the other messages you want, please let me know, @ianlayton

**Comment by ianlayton** [comment]
Trimmed up the wording a bit...

1. Your payment has been accepted, please continue through the at the door registration line to receive your badge. Please have your ID ready.

2. Your registration has been accepted, please continue through the at the door registration line to finish payment and received your badge. Please have your payment of {} and ID ready.

3. Your registration has been accepted, please continue through the at the door registration line to finish payment and received your badge. Please have your payment of {} and ID ready.

4. Your registration has been accepted, please continue through the at the door registration line to received your badge.

5. Your registration has been accepted, please continue through the at the door registration line to received your badge. Please have your ID ready.

**Comment by jmdawson** [comment]
3 is not configured for dynamic pricing, so I reworded it as "please have your payment and ID ready." All of this is up on staging.

**Comment by ianlayton** [comment]
All is good
