### ISSUE TITLE
Updating badge information is forcing a change in registration level

### ISSUE THREAD

**Issue by ianlayton** [MidwestFurryFandom/mff-rams-plugin#133]
If a user attempts to update their information via the website, there doesn't appear to be an option to keep the same registration level.

The person in the screen shot below just has a standard level badge.

**Comment by kitsuta** [comment]
Someday I'm going to rip out these badge level buttons and I will never have to deal with them again and I will be _so. Happy._

... by when I mean, I'll fix this as nonbillable tonight after dinner.
