### ISSUE TITLE
Number of tables not correctly pluralized

### ISSUE THREAD

**Issue by jmdawson** [MidwestFurryFandom/mff-rams-plugin#18]
> Your group will have 1 Dealers Den tables.

**Comment by kitsuta** [comment]
Isn't this de facto fixed now that we use the proper table name in (hopefully) all such cases? It should now print "Your group will have a Single Table in the Dealers Den."

**Comment by jmdawson** [comment]
Reviewing the emails being sent out, it looks like this has been dealt with.
