### ISSUE TITLE
Shirt sizes not being saved

### ISSUE THREAD

**Issue by ianlayton** [MidwestFurryFandom/mff-rams-plugin#38]
Shirt sizes for sponsor levels aren't being saved correctly. You can see an example of this here:

http://rams.test.furfest.org/rams/registration/history?id=9056b402-f3b0-43cb-a9a2-7788ddeead58

Notice the size is initially saved in 'unpaid preregistration' segment, but being overwritten as 'no shirt' when payment goes through in the 'created' segment

**Comment by kitsuta** [comment]
Oh, that's strange. There is likely a rogue presave adjustment at fault. I'll look into it when I'm back at the computer tonight!

**Comment by jmdawson** [comment]
Also done.
