### ISSUE TITLE
No email on dealer cancellation

### ISSUE THREAD

**Issue by jmdawson** [MidwestFurryFandom/mff-rams-plugin#43]
When an admin cancels a dealer's application (from waitlisted), no email goes out. Shouldn't one be sent to document the change?

**Comment by kitsuta** [comment]
This is as-designed, in that I expect most admin cancellations would be at the specific request of the dealer.

If we want the option of a notification, I'd add a 'cancel' button to the same form that sends an email for waitlist/decline to keep the UI consistent.

**Comment by jmdawson** [comment]
We need to follow up w/ Brendan on what he wants here.

**Comment by kitsuta** [comment]
@jmdawson Did we get the information we needed? I can't complete this issue as-is.

**Comment by jmdawson** [comment]
Then it gets punted until next iteration.

**Comment by jmdawson** [comment]
Response from Brendan: This behavior is fine.

> I've been using Cancelled to indicate that a previously approved dealer has decided that they will not be able to take their table, or that I've cancelled an approved dealer for nonpayment. In both cases, there is no need for an automated email since I have sent out emails to the dealers concerning the change in status. I also post the reason for the cancellation in the Admin Remarks section.I use Declined for a dealer who had previously been waitlisted and will no longer be on the waiting list. Usually this is because they will be sharing a table with another dealer, in which case they'll need to get the membership payment info.
