### ISSUE TITLE
Update language for Promo Code Box

### ISSUE THREAD

**Issue by jmdawson** [MidwestFurryFandom/mff-rams-plugin#45]
Update the promo code box to be a "Registration Code" box. Might be some related tweaks to make.

**Comment by jmdawson** [comment]
From a consistency perspective, I'd like to get this done in It1. I'll work on it.

**Comment by kitsuta** [comment]
![image](https://user-images.githubusercontent.com/7198215/40580034-082297bc-6104-11e8-89a2-7e0f0a6be729.png)
Is this acceptable for this issue?

**Comment by jmdawson** [comment]
I like it. Someone else will need to weigh in. @ianlayton @hugmonster ?

**Comment by ianlayton** [comment]
I’m not sure have actually used this feature in the past, but the wording is good for me. I don’t think it will cause confusion.

**Comment by jmdawson** [comment]
We didn't use it last year. We need it this year for agents, but also to support the discounted badges you and Cheetah mentioned.
