### ISSUE TITLE
Cancelation policy change

### ISSUE THREAD

**Issue by ianlayton** [MidwestFurryFandom/mff-rams-plugin#46]
We are changing our policy on refunds. 

in disclaimers.html, please change:

Your registration is refundable until the close of preregistration on Nov 17, 2017. Please contact registration to request a refund before that date. Refunds can only be processed to the purchasing card.

To:

**Purchased registration are non-refundable.** Please contact registration for other options before the close of preregistration on Nov 18, 2018.

(make the bolded text red also)

In attendee_confirmation.html, please remove:

Your registration may be cancelled and refunded until preregistration closes on Friday, November 17, 2017. Please email registration@furfest.org to request a cancellation and refund.

**Comment by jmdawson** [comment]
<img width="783" alt="screen shot 2018-05-24 at 22 16 56" src="https://user-images.githubusercontent.com/910490/40524460-3fff27fa-5fa0-11e8-8a17-0eab1eb2a05c.png">
@ianlayton Does this meet your needs?

**Comment by ianlayton** [comment]
Can we roll back these changes please?

**Comment by jmdawson** [comment]
Done.
