### ISSUE TITLE
Attractions tab

### ISSUE THREAD

**Issue by ianlayton** [MidwestFurryFandom/mff-rams-plugin#50]
Where a person uses the link in the email to view/edit their registration or to fill in a prefilled registration, they are being show an "attractions" tab.

![capture](https://user-images.githubusercontent.com/11669617/40556260-a73b44e6-6011-11e8-9759-6a21890d1311.PNG)

Unless this is going to be used for something, can this be suppressed to eliminate confusion.

**Comment by kitsuta** [comment]
Attractions is a REALLY cool new feature in the system so I'd definitely
encourage taking advantage of it!

But also it doesn't make much sense to show the tab when there's no
attractions set up.

**Comment by ianlayton** [comment]
I'm guessing it's used for signing up for extra "events"? If so, yeah, I can see that being something interesting down the road, but it's just not something we have a need for at this point :)

**Comment by jmdawson** [comment]
I think we should talk to the programming department before taking away features they may use. What use a programming department if not to handle programming themselves?

**Comment by kitsuta** [comment]
Yes, that is what I meant by not showing the tab when there's no attractions set up.

**Comment by ianlayton** [comment]
Hiding when nothing is there is perfect...keeps the option there if we decide to use it
