### ISSUE TITLE
Update Dealer Rules

### ISSUE THREAD

**Issue by jmdawson** [MidwestFurryFandom/mff-rams-plugin#58]
Update the template(s) to be consistent with the following content:

> Dealer Rules and Information
> Your displays and products cannot block the aisles or walkways, but must remain within the table or booth space purchased.
> No selling out of a hotel room, away from the dealer area, or away from your table.
> A list of confirmed dealers will be posted to the web site and will be included in our ConBook. This listing will include your business name and the description of your merchandise from your application, along with a link to your website if one was listed on your dealer application. Dealers are encouraged to check their listing on the web site and promptly request any changes or corrections.
> Advertising space is available in our convention book. If you are interested in purchasing an ad please contact Midwest Furfest Publications <publications@furfest.org>.
> You are required to collect Illinois sales tax at MFF. You are not required to have an Illinois business license, but if you wish to obtain one you may do so at http://www.revenue.state.il.us/Businesses/register.htm . MFF will be providing sales tax reporting forms at the con to those dealers who do not have an Illinois business license. We are required to provide a list of our dealers to IDOR, but we will not be collecting tax payments from our dealers.
> An email will be sent to all dealers about three weeks before Midwest Furfest with details on parking and unloading access, and any other information you may need before arriving.
> Any questions regarding Dealers Den operations should be directed to Midwest FurFest Dealers Room <dealers@furfest.org>
> If for any reason you are unable to deal at Midwest FurFest, please notify us promptly. Full refunds can be made if we receive your cancellation prior to 11:59pm CDT on Monday, Jul 16. After that date, refunds are possible only if we are able to resell your space.
> (TENTATIVE) DEALERS DEN HOURS: 
> Thursday 
> TBA Dealer set-up
> 
> Friday 
> 10am -- 1pm Dealer set-up 
> 1pm -- 7pm Open for sales
> 
> Saturday 
> 9am -- 10am Dealer set-up 
> 10am -- 6pm Open for sales
> 
> Sunday
> 9am -- 10am Dealer set-up 
> 10am -- 4pm Open for sales 
> 4pm -- 7pm Dealer tear-down
> 
> 
> Sincerely,
> Midwest Furfest Dealers Room

**Comment by jmdawson** [comment]
Additional details:
1. Locally, from the latest staging, create a branch to reflect this work (such as update-dealer-rules)
1. Commit the updates to the appropriate template files (https://github.com/MidwestFurryFandom/mff-rams-plugin/blob/mff-staging/mff_rams_plugin/templates/static_views/dealerRules.html)
1. Submit a pull-request to merge the changes back into mff-staging

**Comment by jmdawson** [comment]
Ah-hah! The rules getting sent out are the MAGFest rules, not the MFF rules. MFF rules we have in the system might already be correct, but they are not being applied. This might actually be a VMearl question.

It's also, really, an iteration2 item. Or maybe 1.5.

**Comment by SkylerRingtail** [comment]
Does this mean that you want me to hold off on that change and pull request
right now?

**Comment by jmdawson** [comment]
Yes. I'm going to close this an open a ticket for the actual misbehavior.
