### ISSUE TITLE
Dealers created by admin interface have bad value in email

### ISSUE THREAD

**Issue by jmdawson** [MidwestFurryFandom/mff-rams-plugin#59]
Created a dealer through the Admin interface, and the email for the badge created for that dealer ended up thus: `{dawson@vt.edu,""}`

Consultation with @kitsuta suggests this is because the waitlist/decline explanation text box is also called 'email,' and so it is getting stored as a list.

**Comment by kitsuta** [comment]
Specifically, this bit here: https://github.com/MidwestFurryFandom/rams/pull/228/files#diff-0dcf914548acaf592fa4f81df8a6f9dfL178
