### ISSUE TITLE
Another mention of refunds in the disclaimers

### ISSUE THREAD

**Issue by ianlayton** [MidwestFurryFandom/mff-rams-plugin#68]
4th bullet point down...need to change:

"Midwest Furfest has a one badge per person policy. If you purchase multiple badges (for your family, friend, or as a gift), please ensure that each badge is purchased in the name of the individual who the badge is intended for. You may use the same email address for multiple badges so any surprises aren't ruined. The purchaser retains sole ownership of the badge until the end of preregistration and may request a refund of a purchased badge."

to:

"Midwest Furfest has a one badge per person policy. If you purchase multiple badges (for your family, friend, or as a gift), please ensure that each badge is purchased in the name of the individual who the badge is intended for. You may use the same email address for multiple badges so any surprises aren't ruined. The purchaser retains sole ownership of the badge until the end of preregistration and may request a transfer or rollover of a purchased badge until that time."

**Comment by jmdawson** [comment]
Kinda duplicated by #69 but this has the details of the change (last sentence)

**Comment by ianlayton** [comment]
Please cancel this request as we are allowing refund again.
