### ISSUE TITLE
Add ability to delete duplicate dealer applications

### ISSUE THREAD

**Issue by jmdawson** [MidwestFurryFandom/mff-rams-plugin#75]
I mean, this is basically the ability to delete dealer applications, period.

**Comment by kitsuta** [comment]
Which applications, art show?

**Comment by jmdawson** [comment]
Dealer applications. Art show requests would go on the art show project.

**Comment by kitsuta** [comment]
Oh right, I forgot we just changed it to stop deleting those when declined!
