### ISSUE TITLE
Incorrect date in reminder email

### ISSUE THREAD

**Issue by ianlayton** [MidwestFurryFandom/mff-rams-plugin#77]
In the "Midwest FurFest Badge Confirmation Reminder"

"We're going to delete all un-accepted preregistrations at 11:59pm CST on Saturday, Nov 10, so please make sure to fill out the form before then."

This should match the end of preregistraton, which is Friday, Nov 16

**Comment by jmdawson** [comment]
That date is the placeholder deadline, which is separate from the prereg takedown date.

That in mind, is there any reason you can think of that you'd want to keep the placeholder deadline separate, before I go and change this? (It's not an expensive change, I just want to keep our info as consistent as possible across the year.)

**Comment by jmdawson** [comment]
Done and deployed.
